services:
  mysql:
    image: mysql:8.0
    container_name: project-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - project-network

  backend:
    image: project-backend:1.0
    container_name: project-backend
    ports:
      - "8083:8080"
    depends_on:
      - mysql
    networks:
      - project-network

  frontend:
    image: project-frontend:1.0
    container_name: project-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - project-network

volumes:
  mysql_data:

networks:
  project-network:
    driver: bridge
